### ISSUE TITLE
TurtleTrendFollow_cBot: zlepseni rizeni rizika

### ISSUE THREAD

**Issue by GeorgeFreelanceDeveloper** [GeorgeFreelanceDeveloper/cTraderBots#35]
Prosim o pridani hard stop loss pri zadavani obchodu na burzu a pak nasledne trailovani stop lossu dle pravidel. Nepouzivat ukonceni pozice botem, protoze muze dojit k vypadku bota nebo rychlemu spike pohybu kdy bot nestihne zareagovat a mohli bychom brat vetsi ztratu nebo mensi zisk.

Vetev: fix/add-hard-stop-loss-to-turtle

**Comment by LucyFreelanceDeveloper** [comment]
**Bylo provedeno ve vetvi:** [Pull request 36](https://github.com/GeorgeFreelanceDeveloper/cTraderBots/pull/36)

**Comment by GeorgeFreelanceDeveloper** [comment]
Opraveno a zamergovano do masteru
