### ISSUE TITLE
TurtleTrendFollow_cBot: zjednoduseni spravy otevrenych obchodu

### ISSUE THREAD

**Issue by GeorgeFreelanceDeveloper** [GeorgeFreelanceDeveloper/cTraderBots#39]
Prosim o zjednoduseni spravy otevrenych obchodu, tak aby bot pri otevreni pozice k pozici pridal label "TurtleTrendFollow_cBot-${level}" a pak pri kontrole otevrenych pozic pracoval s timto labelem misto pamatovani si id tradu.

Zrusit promenne tradeId1 a tradeId2, ktere se drive pouzivali pro zapamatovani si id obchodu.

Vetev: feature/simplify-management-positions

**Comment by LucyFreelanceDeveloper** [comment]
updated in pull request [40](https://github.com/GeorgeFreelanceDeveloper/cTraderBots/pull/40)

**Comment by LucyFreelanceDeveloper** [comment]
Vyvinuto a zamergovano do masteru
